In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/Superstore.csv')

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2018-138688,12-06-2018,16-06-2018,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
# df['columnName'].value_counts(dropna=False)

# this code counts all of the data in the column we have specified.but does not count null values

In [5]:
df['Region'].value_counts(dropna=False)

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [6]:
df['Region'].value_counts(dropna=True)

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [7]:
df['Postal Code'].value_counts()

Postal Code
10035.0    263
10024.0    230
10009.0    229
94122.0    203
10011.0    193
          ...
98208.0      1
79605.0      1
61761.0      1
72762.0      1
93405.0      1
Name: count, Length: 630, dtype: int64

In [8]:
df['Sub-Category'].value_counts()

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [9]:
# To check the number of null (missing/NaN) values in each column:
df.isna().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country/Region     0
City               0
State              0
Postal Code       11
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
dtype: int64

In [10]:
# sort data
# df.sort_values('columnname')

# this code sorts the column we specify in the form of low to high.

In [11]:
df.sort_values('Sales', ascending=False)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2697,2698,CA-2016-145317,18-03-2016,23-03-2016,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
6826,6827,CA-2018-118689,02-10-2018,09-10-2018,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
8153,8154,CA-2019-140151,23-03-2019,25-03-2019,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
2623,2624,CA-2019-127180,22-10-2019,24-10-2019,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4190,4191,CA-2019-166709,17-11-2019,22-11-2019,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,2107,US-2016-152723,26-09-2016,26-09-2016,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,...,75150.0,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876,1,0.8,-1.4016
4711,4712,CA-2016-112403,31-03-2016,31-03-2016,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,...,19120.0,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852,1,0.7,-0.5964
8658,8659,CA-2018-168361,21-06-2018,25-06-2018,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,...,60623.0,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,1,0.8,-1.3376
9292,9293,CA-2019-124114,02-03-2019,02-03-2019,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,...,76706.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,1,0.8,-0.9452
4101,4102,US-2019-102288,19-06-2019,23-06-2019,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,77095.0,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100

In [12]:
df.sort_values('Sales', ascending=True)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4101,4102,US-2019-102288,19-06-2019,23-06-2019,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,77095.0,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100
9292,9293,CA-2019-124114,02-03-2019,02-03-2019,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,...,76706.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,1,0.8,-0.9452
8658,8659,CA-2018-168361,21-06-2018,25-06-2018,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,...,60623.0,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,1,0.8,-1.3376
4711,4712,CA-2016-112403,31-03-2016,31-03-2016,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,...,19120.0,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852,1,0.7,-0.5964
2106,2107,US-2016-152723,26-09-2016,26-09-2016,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,...,75150.0,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876,1,0.8,-1.4016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4190,4191,CA-2019-166709,17-11-2019,22-11-2019,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
2623,2624,CA-2019-127180,22-10-2019,24-10-2019,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
8153,8154,CA-2019-140151,23-03-2019,25-03-2019,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
6826,6827,CA-2018-118689,02-10-2018,09-10-2018,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
2697,2698,CA-2016-145317,18-03-2016,23-03-2016,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784

In [13]:
#to sort specific rows
df.sort_values('Sales')[20:51:2]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
8965,8966,CA-2019-106691,06-11-2019,12-11-2019,Standard Class,CC-12370,Christopher Conant,Consumer,United States,Houston,...,77070.0,Central,OFF-BI-10000145,Office Supplies,Binders,Zipper Ring Binder Pockets,1.248,2,0.8,-1.9344
2346,2347,CA-2018-159373,13-03-2018,18-03-2018,Standard Class,LT-17110,Liz Thompson,Consumer,United States,San Antonio,...,78207.0,Central,OFF-BI-10004141,Office Supplies,Binders,Insertable Tab Indexes For Data Binders,1.272,2,0.8,-2.1624
3766,3767,CA-2018-163153,21-03-2018,25-03-2018,Standard Class,DM-12955,Dario Medina,Corporate,United States,Houston,...,77036.0,Central,OFF-AR-10001868,Office Supplies,Art,Prang Dustless Chalk Sticks,1.344,1,0.2,0.5040
2427,2428,CA-2018-169922,11-06-2018,17-06-2018,Standard Class,MZ-17515,Mary Zewe,Corporate,United States,Arlington,...,76017.0,Central,OFF-BI-10003784,Office Supplies,Binders,Computer Printout Index Tabs,1.344,4,0.8,-2.1504
6597,6598,CA-2016-169257,06-06-2016,12-06-2016,Standard Class,SV-20785,Stewart Visinsky,Consumer,United States,Jacksonville,...,32216.0,South,OFF-BI-10002557,Office Supplies,Binders,Presstex Flexible Ring Binders,1.365,1,0.7,-0.9100
7356,7357,CA-2018-114748,09-10-2018,14-10-2018,Standard Class,MZ-17335,Maria Zettner,Home Office,United States,Phoenix,...,85023.0,West,OFF-AR-10001315,Office Supplies,Art,Newell 310,1.408,1,0.2,0.1584
2213,2214,CA-2019-129378,01-10-2019,02-10-2019,First Class,NS-18505,Neola Schneider,Consumer,United States,San Jose,...,95123.0,West,OFF-BI-10002012,Office Supplies,Binders,Wilson Jones Easy Flow II Sheet Lifters,1.440,1,0.2,0.5040
9304,9305,US-2017-163433,18-04-2017,22-04-2017,Second Class,MP-17965,Michael Paige,Corporate,United States,Mcallen,...,78501.0,Central,OFF-BI-10000320,Office Supplies,Binders,GBC Plastic Binding Combs,1.476,1,0.8,-2.2878
3213,3214,CA-2018-132409,26-05-2018,01-06-2018,Standard Class,TH-21235,Tiffany House,Corporate,United States,Philadelphia,...,19134.0,East,OFF-AR-10001919,Office Supplies,Art,"OIC #2 Pencils, Medium Soft",1.504,1,0.2,0.1692
7494,7495,US-2019-160836,11-09-2019,16-09-2019,Standard Class,CC-12475,Cindy Chapman,Consumer,United States,Houston,...,77070.0,Central,OFF-AP-10001626,Office Supplies,Appliances,Commercial WindTunnel Clean Air Upright Vacuum...,1.556,2,0.8,-4.2012
5540,5541,US-2019-150595,22-05-2019,26-05-2019,Standard Class,LE-16810,Laurel Elliston,Consumer,United States,Chicago,...,60653.0,Central,OFF-BI-10003274,Office Supplies,Binders,"Avery Durable Slant Ring Binders, No Labels",1.592,2,0.8,-2.6268
5342,5343,US-2016-168501,21-11-2016,27-11-2016,Standard Class,JK-15325,Jason Klamczynski,Corporate,United States,Dallas,...,75220.0,Central,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,1.632,1,0.2,0.5508
2727,2728,CA-2019-119193,22-12-2019,24-12-2019,First Class,SK-19990,Sally Knutson,Consumer,United States,Toledo,...,43615.0,East,OFF-BI-10000848,Office Supplies,Binders,Angle-D Ring Binders,1.641,1,0.7,-1.3128
61,62,CA-2018-111682,17-06-2018,18-06-2018,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,...,12180.0,East,OFF-AR-10001868,Office Supplies,Art,Prang Dustless Chalk Sticks,1.680,1,0.0,0.8400
8979,8980,CA-2017-150413,19-10-2017,24-10-2017,Second Class,CS-11860,Cari Schnelling,Consumer,United States,Dallas,...,75220.0,Central,OFF-BI-10000404,Office Supplies,Binders,Avery Printable Repositionable Plastic Tabs,1.720,1,0.8,-2.8380
8982,8983,CA-2018-110898,06-03-2018,12-03-2018,Standard Class,LC-16870,Lena Cacioppo,Consumer,United States,Chicago,...,60623.0,Central,OFF-BI-10004656,Office Supplies,Binders,Peel & Stick Add-On Corner Pockets,1.728,4,0.8,-2.7648

In [14]:
# Renaming column
df.rename(columns={'Region':'all Region','Sales':'all Sales'}, inplace=True)
# inplace true means make changes in existing df

In [15]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,all Region,Product ID,Category,Sub-Category,Product Name,all Sales,Quantity,Discount,Profit
0,1,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2018-138688,12-06-2018,16-06-2018,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [17]:
#renaming to previous one
df.rename(columns={' all Region':'Region',"all Sales":"Sales"},inplace=True)

In [18]:
# df.columns

# this helps to check all column names

df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State', 'Postal Code', 'all Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [19]:
# Defining new column
# create a new column
# called as feature construction

In [21]:
df['total sales']= df['Sales']* df['Quantity']
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,all Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,total sales
0,1,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,523.9200
1,2,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2195.8200
2,3,CA-2018-138688,12-06-2018,16-06-2018,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,29.2400
3,4,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,4787.8875
4,5,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,44.7360

In [23]:
df['Profit']

0        41.9136
1       219.5820
2         6.8714
3      -383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Profit, Length: 9994, dtype: float64

In [24]:
# apply function

# during production we apply this function

In [26]:
# method 1
df['Profit']=df['Profit'].apply(lambda x:x*2)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,all Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,total sales
0,1,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,83.8272,523.9200
1,2,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,439.1640,2195.8200
2,3,CA-2018-138688,12-06-2018,16-06-2018,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,13.7428,29.2400
3,4,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-766.0620,4787.8875
4,5,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,5.0328,44.7360

In [27]:
# method 2 : by broadcasting
df['Profit']*2

0        167.6544
1        878.3280
2         27.4856
3      -1532.1240
4         10.0656
          ...
9989      16.4112
9990      62.5328
9991      77.5728
9992      53.2800
9993     291.7920
Name: Profit, Length: 9994, dtype: float64

In [29]:
df['all Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [30]:
# Group By:

In [34]:
# use group by to show region wise sales
obj= df.groupby('all Region')
print('Total sales in east region: ', obj.get_group('East')['Sales'].sum())
print('Total sales in West region: ', obj.get_group('West')['Sales'].sum())
print('Total sales in South region: ', obj.get_group('South')['Sales'].sum())
print('Total sales in Central region: ', obj.get_group('Central')['Sales'].sum())

Total sales in east region:  678781.24
Total sales in West region:  725457.8245
Total sales in South region:  391721.905
Total sales in Central region:  501239.8908

In [39]:
#to show category wise total profit
obj1= df.groupby('Category')
print('total profit in furniture: ',obj1.get_group('Furniture')['Profit'].sum())
print('total profit in office supplies: ',obj1.get_group('Office Supplies')['Profit'].sum())
print('total profit in technology: ',obj1.get_group('Technology')['Profit'].sum())

total profit in furniture:  36902.54560000001
total profit in office supplies:  244981.6016
total profit in technology:  290909.8962

In [44]:
# to create groups and acess data group wise
df['Category'].unique()
obj=df.groupby('Category')
print(obj.get_group('Furniture'))
print(obj.get_group('Furniture')['Profit'].sum())

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2018-152156  08-11-2018  11-11-2018    Second Class
1          2  CA-2018-152156  08-11-2018  11-11-2018    Second Class
3          4  US-2017-108966  11-10-2017  18-10-2017  Standard Class
5          6  CA-2016-115812  09-06-2016  14-06-2016  Standard Class
10        11  CA-2016-115812  09-06-2016  14-06-2016  Standard Class
...      ...             ...         ...         ...             ...
9962    9963  CA-2017-168088  19-03-2017  22-03-2017     First Class
9964    9965  CA-2018-146374  05-12-2018  10-12-2018    Second Class
9980    9981  US-2017-151435  06-09-2017  09-09-2017    Second Class
9989    9990  CA-2016-110422  21-01-2016  23-01-2016    Second Class
9990    9991  CA-2019-121258  26-02-2019  03-03-2019  Standard Class

     Customer ID     Customer Name      Segment Country/Region  \
0       CG-12520       Claire Gute     Consumer  United States
1       CG-12520       Claire Gute     Consumer  United States
3       SO-20335    Sean O'Donnell     Consumer  United States
5       BH-11710   Brosina Hoffman     Consumer  United States
10      BH-11710   Brosina Hoffman     Consumer  United States
...          ...               ...          ...            ...
9962    CM-12655  Corinna Mitchell  Home Office  United States
9964    HE-14800      Harold Engle    Corporate  United States
9980    SW-20455       Shaun Weien     Consumer  United States
9989    TB-21400  Tom Boeckenhauer     Consumer  United States
9990    DB-13060       Dave Brooks     Consumer  United States

                 City  ... all Region       Product ID   Category  \
0           Henderson  ...      South  FUR-BO-10001798  Furniture
1           Henderson  ...      South  FUR-CH-10000454  Furniture
3     Fort Lauderdale  ...      South  FUR-TA-10000577  Furniture
5         Los Angeles  ...       West  FUR-FU-10001487  Furniture
10        Los Angeles  ...       West  FUR-TA-10001539  Furniture
...               ...  ...        ...              ...        ...
9962          Houston  ...    Central  FUR-BO-10004218  Furniture
9964           Newark  ...       East  FUR-FU-10002671  Furniture
9980        Lafayette  ...      South  FUR-TA-10001039  Furniture
9989            Miami  ...      South  FUR-FU-10001889  Furniture
9990       Costa Mesa  ...       West  FUR-FU-10000747  Furniture

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
5     Furnishings  Eldon Expressions Wood and Plastic Desk Access...
10         Tables           Chromcraft Rectangular Conference Tables
...           ...                                                ...
9962    Bookcases  Bush Heritage Pine Collection 5-Shelf Bookcase...
9964  Furnishings  Electrix 20W Halogen Replacement Bulb for Zoom...
9980       Tables                         KI Adjustable-Height Table
9989  Furnishings                             Ultra Door Pull Handle
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...

          Sales Quantity  Discount    Profit  total sales
0      261.9600        2      0.00   83.8272     523.9200
1      731.9400        3      0.00  439.1640    2195.8200
3      957.5775        5      0.45 -766.0620    4787.8875
5       48.8600        7      0.00   28.3388     342.0200
10    1706.1840        9      0.20  170.6184   15355.6560
...         ...      ...       ...       ...          ...
9962   383.4656        4      0.32 -135.3408    1533.8624
9964    13.4000        1      0.00   12.8640      13.4000
9980    85.9800        1      0.00   44.7096      85.9800
9989    25.2480        3      0.20    8.2056      75.7440
9990    91.9600        2      0.00   31.2664     183.9200

[2121 rows x 22 columns]
36902.54560000001

In [45]:
# Merge,join,concat

In [50]:
# Concatenation of data frames

In [49]:
dict1={'id':[464,868,105,979,2424],
       'name':['aab','fadd','dad','dfasd','dffg'],
       'salary':[35000,40000,15000,10000,16000]}
df1=pd.DataFrame(dict1)
df1

     id   name  salary
0   464    aab   35000
1   868   fadd   40000
2   105    dad   15000
3   979  dfasd   10000
4  2424   dffg   16000

In [47]:
dict2={'id':[101,102,103,104,105],
       'name':['jon','setu','vijay','allu','teja'],
       'salary':[12000,22000,28000,18000,16000]}
df2=pd.DataFrame(dict2)
df2

    id   name  salary
0  101    jon   12000
1  102   setu   22000
2  103  vijay   28000
3  104   allu   18000
4  105   teja   16000

In [48]:
df3=pd.concat([df1,df2],ignore_index=True)

df3

     id   name  salary
0   464    aab   35000
1   868   fadd   40000
2   105    dad   15000
3   979  dfasd   10000
4  2424   dffg   16000
5   101    jon   12000
6   102   setu   22000
7   103  vijay   28000
8   104   allu   18000
9   105   teja   16000

In [51]:
# Merge in pandas similar to join in sql
# In pandas, the merge function is used to combine two DataFrames based on a key (or multiple keys).

# It is similar to SQL joins and allows you to perform various types of joins (inner, left, right, outer) to combine rows from different DataFrames.

In [52]:
#df1
dict1={'id':[101,301,300],
       'name':['babita','sangita','ranjita'],
       'salary':[35000,40000,15000]}
df1=pd.DataFrame(dict1)
df1

    id     name  salary
0  101   babita   35000
1  301  sangita   40000
2  300  ranjita   15000

In [53]:
#df2
dict2={'id':[101,102,300,205],
       'name':['akash','suresh','mohit','nilesh'],
       'salary':[12000,22000,28000,18000]}
df2=pd.DataFrame(dict2)
df2

    id    name  salary
0  101   akash   12000
1  102  suresh   22000
2  300   mohit   28000
3  205  nilesh   18000

In [54]:
# inner merge: showing only common ids
pd.merge(df1,df2,on='id',how='inner')

    id   name_x  salary_x name_y  salary_y
0  101   babita     35000  akash     12000
1  300  ranjita     15000  mohit     28000

In [55]:
# left merge :
# all records from left dataframe commen records from right

In [56]:
df3=pd.merge(df1,df2,on='id',how='left')
df3

    id   name_x  salary_x name_y  salary_y
0  101   babita     35000  akash   12000.0
1  301  sangita     40000    NaN       NaN
2  300  ranjita     15000  mohit   28000.0

In [60]:
# right merge:
# comman records from left all records from right

In [58]:
df3=pd.merge(df1,df2,on='id',how='right')
df3

    id   name_x  salary_x  name_y  salary_y
0  101   babita   35000.0   akash     12000
1  102      NaN       NaN  suresh     22000
2  300  ranjita   15000.0   mohit     28000
3  205      NaN       NaN  nilesh     18000

In [59]:
#experiment : nested inner join
pd.merge(df3,pd.merge(df1,df2,on='id',how='inner'),on='id',how='inner')

,id,name_x_x,salary_x_x,name_y_x,salary_y_x,name_x_y,salary_x_y,name_y_y,salary_y_y
0,101,babita,35000.0,akash,12000,babita,35000,akash,12000
1,300,ranjita,15000.0,mohit,28000,ranjita,15000,mohit,28000

In [61]:
df3=pd.merge(df1,df2,on='id',how='outer')
df3

    id   name_x  salary_x  name_y  salary_y
0  101   babita   35000.0   akash   12000.0
1  102      NaN       NaN  suresh   22000.0
2  205      NaN       NaN  nilesh   18000.0
3  300  ranjita   15000.0   mohit   28000.0
4  301  sangita   40000.0     NaN       NaN

In [65]:
# 📘  7: Filtering Rows


data2 = {
    'id': [101, 102, 103, 104, 105],
    'name': ['Arun', 'Nilesh', 'Ajit', 'Prashant', 'Priya'],
    'city': ['Mumbai', 'Pune', 'Surat', 'Gujarat', 'Satara'],
    'age': [45, 75, 88, 44, 86]
}
df5 = pd.DataFrame(data2)
df5

df5[df5['age']>60]

    id    name    city  age
1  102  Nilesh    Pune   75
2  103    Ajit   Surat   88
4  105   Priya  Satara   86

In [64]:
df5[df5["name"] =="Arun"]

    id  name    city  age
0  101  Arun  Mumbai   45

In [66]:
df5[df5["name"].isin(["Arun","Ajit"])]

    id  name    city  age
0  101  Arun  Mumbai   45
2  103  Ajit   Surat   88

In [67]:
# Handling Missing Values

In [68]:
dict1={
    'Duration': [60, 60, 45, 450, 30],
    'Date': ['2020/12/01', '2020/12/01', '2020/12/03', None, '2020/12/05'],
    'Pulse': [110, 117, 109, 104, 109],
    'Calories': [409.1, None, 282.4, 253.3, None]
}

df3 = pd.DataFrame(dict1)
df3

   Duration        Date  Pulse  Calories
0        60  2020/12/01    110     409.1
1        60  2020/12/01    117       NaN
2        45  2020/12/03    109     282.4
3       450        None    104     253.3
4        30  2020/12/05    109       NaN

In [69]:
df3.isnull().sum() # to check null in each col

Duration    0
Date        1
Pulse       0
Calories    2
dtype: int64

In [70]:
df3.dropna() #delete the row with null values

   Duration        Date  Pulse  Calories
0        60  2020/12/01    110     409.1
2        45  2020/12/03    109     282.4

In [71]:
df3

   Duration        Date  Pulse  Calories
0        60  2020/12/01    110     409.1
1        60  2020/12/01    117       NaN
2        45  2020/12/03    109     282.4
3       450        None    104     253.3
4        30  2020/12/05    109       NaN

In [73]:
#replacing null values with mean in calories col
df3["Calories"]=df3["Calories"].fillna(df3["Calories"].mean())
df3

   Duration        Date  Pulse    Calories
0        60  2020/12/01    110  409.100000
1        60  2020/12/01    117  314.933333
2        45  2020/12/03    109  282.400000
3       450        None    104  253.300000
4        30  2020/12/05    109  314.933333

In [76]:
#replacing null values with median in calories col
df3["Calories"]=df3["Calories"].fillna(df3["Calories"].median())
df3
# when there is no outliers in the data, median == mode

   Duration        Date  Pulse    Calories
0        60  2020/12/01    110  409.100000
1        60  2020/12/01    117  314.933333
2        45  2020/12/03    109  282.400000
3       450  2020/12/01    104  253.300000
4        30  2020/12/05    109  314.933333

In [77]:
# replacing null date with most repeated date ie mode
df3["Date"]=df3['Date'].fillna(df3["Date"].mode()[0]) #here 0 is mentioned bcz in tuple of modes, we select the first one (most frequent)
df3

   Duration        Date  Pulse    Calories
0        60  2020/12/01    110  409.100000
1        60  2020/12/01    117  314.933333
2        45  2020/12/03    109  282.400000
3       450  2020/12/01    104  253.300000
4        30  2020/12/05    109  314.933333